package program;

public enum Tipo {
	
	PROGRAM(1,  	  "PALAVRA RESERVADA"),
	LABEL(2,		  "PALAVRA RESERVADA"),
	CONST(3, 		  "PALAVRA RESERVADA"),
	VAR(4, 			  "PALAVRA RESERVADA"),
	PROCEDURE(5,	  "PALAVRA RESERVADA"),
	BEGIN(6,   	      "PALAVRA RESERVADA"),
	END(7,       	  "PALAVRA RESERVADA"),
	INTEGER(8,  	  "PALAVRA RESERVADA"),
	ARRAY(9,    	  "PALAVRA RESERVADA"),
	OF(10,      	  "PALAVRA RESERVADA"),
	CALL(11,    	  "PALAVRA RESERVADA"),
	GOTO(12,    	  "PALAVRA RESERVADA"),
	IF(13,      	  "PALAVRA RESERVADA"),
	THEN(14,     	  "PALAVRA RESERVADA"),
	ELSE(15,     	  "PALAVRA RESERVADA"),
	WHILE(16,    	  "PALAVRA RESERVADA"),
	DO(17, 	    	  "PALAVRA RESERVADA"),
	REPEAT(18,  	  "PALAVRA RESERVADA"),
	UNTIL(19,         "PALAVRA RESERVADA"),
	READLN(20,  	  "PALAVRA RESERVADA"),
	WRITELN(21, 	  "PALAVRA RESERVADA"),
	OR(22,       	  "OPERADOR LOGICO"),
	AND(23, 	 	  "OPERADOR LOGICO"),
	NOT(24,			  "OPERADOR DE NEGAÇÃO"),
	IDENTIFICADOR(25, "IDENTIFICADOR"),
	INTEIRO(26,       "NUMERO INTEIRO"),
	FOR(27,			  "PALAVRA RESERVADA"),
	TO(28,       	  "PALAVRA RESERVADA"),
	CASE(29,     	  "PALAVRA RESERVADA"),
	ADICAO(30, 	 	  "OPERADOR DE ADIÇÃO"),
	SUBTRACAO(31,	  "OPERADOR DE SUBTRAÇÃO"),
	MULTIPLICACAO(32, "OPERADOR DE MULTIPLICAÇAO"),
	DIVISAO(33,		  "OPERADOR DE DIVISÃO"),
	ABRE_COLCH(34,    "CARACTERE ESPECIAL"),
	FECHA_COLCH(35,   "CARACTERE ESPECIAL"),
	ABRE_PAR(36,	  "CARACTERE ESPECIAL"),
	FECHA_PAR(37, 	  "CARACTERE ESPECIAL"),
	ATRIBUICAO(38, 	  "ATRIBUIÇÃO"),
	DOIS_PONTOS(39,   "CARACTERE ESPECIAL"),
	IGUALIDADE(40,	  "IGUALIDADE"),
	MAIOR(41, 		  "OPERADOR RELACIONAL"),
	MAIOR_IGUAL(42,   "OPERADOR RELACIONAL"),
	MENOR(43,		  "OPERADOR RELACIONAL"),
	MENOR_IGUAL(44,   "OPERADOR RELACIONAL"),
	EQUIVALENTE(45,	  "OPERADOR RELACIONAL"),
	VIRGULA(46, 	  "CARACTERE ESPECIAL"),
	PONTO_VIRGULA(47, "CARACTERE ESPECIAL"),
	LITERAL(48, 	  "LITERAL"),
	PONTO(49, 		  "CARACTERE ESPECIAL"),
	PONTO_PONTO(50,   "CARACTERE ESPECIAL"),
	FINAL(51, 		  "DELIMITADOR FINAL");

	int codigo;
	String descricao;
	
	Tipo(int codigo, String descricao)
	{
		this.codigo    = codigo;
		this.descricao = descricao;
	}
}
